FROM node:14

RUN useradd --create-home appuser
WORKDIR /home/appuser

COPY dist /home/appuser/web_app/dist

WORKDIR /home/appuser/web_app

EXPOSE 5000

RUN ["npm", "install", "-g", "serve"]

CMD ["serve", "-s", "dist"]
