FROM python:3.7.3-stretch

RUN useradd --create-home appuser
COPY / /home/appuser/src
RUN pip install -r /home/appuser/src/requirements.txt
WORKDIR /home/appuser
USER appuser

RUN ["pwd"]
RUN ["python", "-m", "pytest"]

#TODO - Add worker processes to gunicorn below 
CMD [ "gunicorn", "--bind", "0.0.0.0:5003", "--pythonpath", "/home/appuser/src", "wsgi" ]